name: date_convert_helper
description: "Date Convert Helper, this package will provide you to convert any DateTime data at your desire date format."
version: 1.0.0
homepage: https://github.com/mirzamahmud/date_convert_helper
repository: https://github.com/mirzamahmud/date_convert_helper
issue_tracker: https://github.com/mirzamahmud/date_convert_helper/issues

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cloud_firestore: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
